---
title: 'MR Data Challenge: Data Generation'
author: "Joy Shi"
header-includes:
    - \usepackage{caption}
output:
  pdf_document:
    df_print: kable
  html_document: default
  word_document: default
fontsize: 12 pt
editor_options: 
  chunk_output_type: console
---

# Setting working directory and loading packages
```{r setup, include=FALSE}

rm(list=ls())

library(tidyverse)

# library(gfoRmula)
# library(MRchecks)
# library(survival)
# library(survminer)
# library(parallel)
# library(tidyverse)
# library(ivtools)

```

# Generating data
```{r creating placeholder variables for part 2, eval=F}

n <- 50000
set.seed(5843)

Z <- do.call(cbind,lapply(runif(11, min=0.10, max=0.5), function(i){rbinom(n, 2, i)}))
colnames(Z) <- paste("Z", seq(1:11), sep="")

id <- seq(1:n)
U0 <- rnorm(n, 0, 1)
U1 <- rnorm(n, 0, 1)
A0 <- rnorm(n, 25, 5)
A1 <- rnorm(n, 25, 5)
Y0 <- rbinom(n, 1, 0.025)
Y1 <- rbinom(n, 1, 0.025)

sim.data <- data.frame(id=id, time=0, Z, U=U0, A=A0, Y=Y0) %>%
  rbind(data.frame(id=id[Y0==0], time=1, Z[Y0==0,], U=U1[Y0==0], A=A1[Y0==0], Y=Y1[Y0==0]))

```
```{r importing data and parameters from part 2}
pregdata <- read.csv("pregdata.csv")
parameters <- readRDS("parameters.RDS")

```
```{r creating loop for generating longitudinal data}

# Function parameters
#  - k: the total number of time points (including baseline); 
#       i.e., the final time point will have t = k-1 
#  - data: name of the dataset which contains data on the first 2 time points
#  - seed: value for seed used in the function
#  - beta_ZU: magnitude of the effect of Z on U_k (note: needs to be a vector
#             of length 11)
#  - beta_UU: magnitude of the effect of U_(k-1) on U_k
#  - beta_AU: magnitude of the effect of each standard deviation increase in 
#             A_(k-1) on U_k
#  - beta_ZA_base: effect of Z on A at time 0 
#  - beta_ZA_slope: change in effect of Z on A over time
#  - beta_UA: magnitude of the effect of U_k on A_k
#  - beta_AA: magnitude of the effect of A_(k-1) on A_k
#  - hazard: baseline hazard of developing the outcome
#  - beta_UY: magnitude of the effect of U_k on Y_(k+1)
#  - beta_ZY: magnitude of the effect of Z on Y_(k+1)
#  - beta_AY_base: magnitude of the effect of (A_k) on Y_(k+1); vector to allow
#                  for the effect to change over time
#  - beta_AY_time: multiplier for the effect of A_(k-1) on Y_(k+1); i.e.
#                  a value <1 will allow for the effect of earlier exposures to
#                  be smaller

datagen <- function(k, data, seed,
                    beta_ZU, beta_UU, beta_AU, 
                    beta_ZA_base, beta_ZA_slope, beta_UA, beta_AA,
                    hazard, beta_UY, beta_ZY, beta_AY_base, beta_AY_time){
  temp.data <- data
  set.seed(seed)
  
  # Generating follow-up data from t=2 to t=k
  for (i in 2:(k-1)){
    
    # Pulling out relevant values from previous time points
    data_ <- temp.data[which(temp.data$time==i-1 & temp.data$Y==0),]
    id_ <- data_[["id"]]
    n_ <- length(id_)
    U_ <- data_[["U"]]
    A_ <- data_[["A"]]
    Z_ <- as.matrix(data_[, grepl("Z", names(temp.data))])
    
    # Simulating new values for U, A, and Y at time i
    U <- rnorm(n_, (beta_ZU %*% t(Z_) + beta_UU*U_ + beta_AU*((A_-50)/10)), 1)
    A <- rnorm(n_, 25+(beta_ZA_base + beta_ZA_slope*i)%*%t(Z_) + beta_UA*U_ + 
          beta_AA*t(A_/2), 5)
    Y <- rbinom(n_, 1, plogis(log(hazard/(1-hazard)) + beta_ZY%*%t(Z_) + beta_UY*U +
          beta_AY_base[i+1]*(A-50)/10 + (beta_AY_base[i]*beta_AY_time*((A_-50)/10))))
             
    # Adding data for new time point to existing dataset
    new.data <- data.frame(id=id_, time=i, Z_, U=U, A=A, Y=Y)
    temp.data <- rbind(temp.data, new.data)
    
  }
  return(temp.data)
}
  

```
```{r parameters for datagen function}

k <- 6
seed <- 65402
beta_ZU <- c(rep(0, 8), 0.25, 0.10, 0.3)
beta_UU <- 0.5
beta_AU <- 0.35
beta_ZA_base <- parameters[[2]]
beta_ZA_slope <- parameters[[3]]/3
beta_ZA_slope[2] <- 0  
beta_UA <- 5
beta_AA <- 0.5
hazard <- 0.01
beta_UY <- 0.3
beta_ZY <- c(rep(0, 3), 0.1, 0.05, 0.3, 0.2, 0.01, rep(0, 3))
beta_AY_base <- c(0.2, 0.3, 0.7, 0.3, 0.2, 0.1)
beta_AY_time <- 0.5

```
```{r formatting data from part 2 and generating remaining data}

pregdata.final <- pregdata %>%
  mutate(id=row_number()) %>%
  select(id, Z1, Z2, Z3, Z4, Z5, Z6, Z7, Z8, Z9, Z10, Z11,
    A0, A1, U0, U1) %>%
  pivot_longer(cols=A0:U1, names_to = c('.value', 'time'),
    names_pattern="(.*?)(\\d+)") %>%
  mutate(Y=ifelse(time==0, 
    rbinom(nrow(pregdata), 1, plogis(log(hazard/(1-hazard)) + 
      beta_ZY%*%t(pregdata[,grepl("Z[0-9]", colnames(pregdata))]) + 
      beta_UY*pregdata$U0 + beta_AY_base[1]*((pregdata$A0-50)/10))),
    rbinom(nrow(pregdata), 1, plogis(log(hazard/(1-hazard)) +
      beta_ZY%*%t(pregdata[,grepl("Z[0-9]", colnames(pregdata))]) + 
      beta_UY*pregdata$U1 + beta_AY_base[2]*((pregdata$A1-50)/10) +
      beta_AY_base[1]*0.5*((pregdata$A0-50)/10))))) %>%
  arrange(id, time) %>%
  mutate(drop=ifelse(time==1 & lag(Y)==1, 1, 0)) %>%
  filter(drop==0) %>%
  select(-drop)

final.data <- datagen(data=pregdata.final,
  k=k, seed=seed,
  beta_ZU=beta_ZU, beta_UU=beta_UU, beta_AU=beta_AU,
  beta_ZA_base=beta_ZA_base, beta_ZA_slope=beta_ZA_slope, 
  beta_UA=beta_UA, beta_AA=beta_AA,
  hazard=hazard, beta_UY=beta_UY, beta_ZY=beta_ZY, 
  beta_AY_base=beta_AY_base, beta_AY_time=beta_AY_time)

```
